#!/bin/bash
curl -H 'API-Key: R336LW2OYPBDWOAYEPYUKD6EX4ZS37RHFQBA' https://api.vultr.com/v1/server/bandwidth?SUBID=24461981 | python -m json.tool > log1
all_count=`cat log1 |wc -l`
echo $all_count
half_count=`expr $all_count / 2`
echo $half_count
cat log1 | grep -A $half_count "outgoing_bytes"  > log2
rm log1
sed -i '$d' log2
sed -i '1d' log2
sed -i '$d' log2
sed -i '/,/d' log2
sed -i '1~2d' log2
BANDUSAGE=`awk -F '"' '{sum+=$2};END {print sum}' log2`
echo "BANDUSAGE= $BANDUSAGE"
rm log2
